version: "3.8"

services:
  tomcat:
    image: tomcat-server
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8081:8080

volumes:
  my-db:
